import type { LabParams, MaterialState } from './params';

/**
 * 4 幕灯光预设。数值来源：docs/07-灯光与材质系统.md §7。
 * 每幕的 fog 颜色与 fill 天空色必须同色系，否则远处物体会跳出雾。
 */
export interface LightPreset {
  id: string;
  name: string;
  note: string;
  apply: Partial<LabParams>;
}

export const LIGHT_PRESETS: LightPreset[] = [
  {
    id: 'preview',
    name: '预览（中性 · 默认）',
    note: '编辑器默认预览光：亮堂、中性、贴图清晰，对标系统 3D 查看器。想回到游戏内 god-view 灯光就点 Act1-4。',
    apply: {
      keyAzimuth: -35,
      keyElevation: 34,
      keyIntensity: 2.6,
      keyColor: '#FFD2A1',
      fillSkyColor: '#828C9E',
      fillSkyIntensity: 0.5,
      fillGroundColor: '#8A7A5E',
      fillGroundIntensity: 0.3,
      rimColor: '#FFEAB8',
      rimIntensity: 0.45,
      ambientColor: '#565A72',
      ambientIntensity: 0.5,
      shadowEnd: 0.5,
      shadowMult: 0.75,
      exposure: 1.6,
      vignette: 0.06,
      gradeShadowMult: 0.95,
      gradeShadowMix: 0.12,
      halftoneStrength: 0.1,
    },
  },
  {
    id: 'act1',
    name: 'Act1 城郊公路（黄昏）',
    note: '低仰角长影是这幕的记忆点。key 18° 压得很低，黄昏感全靠它。',
    apply: {
      keyAzimuth: -35,
      keyElevation: 18,
      keyIntensity: 1.15,
      keyColor: '#FFB066',
      fillSkyColor: '#4A6B9B',
      fillSkyIntensity: 0.35,
      fillGroundColor: '#6B5A3E',
      fillGroundIntensity: 0.15,
      rimColor: '#FFE0A0',
      rimIntensity: 0.5,
      ambientColor: '#2A2438',
      ambientIntensity: 0.1,
      fogColor: '#8A5A3C',
      fogDensity: 0.02,
      gradeShadowMult: 0.78,
      gradeLightMix: 0.16,
      gradeShadowSat: 1.15,
    },
  },
  {
    id: 'act2',
    name: 'Act2 废弃仓库（顶灯）',
    note: '顶光 + 顶视角 = 平色陷阱最严重的一幕。真正上项目时必须启用角色光把仰角压回 35°。',
    apply: {
      keyAzimuth: 20,
      keyElevation: 70,
      keyIntensity: 1.0,
      keyColor: '#FFF0D0',
      fillSkyColor: '#2A2B45',
      fillSkyIntensity: 0.22,
      fillGroundColor: '#1A1520',
      fillGroundIntensity: 0.1,
      rimColor: '#89C7E8',
      rimIntensity: 0.35,
      ambientColor: '#14121F',
      ambientIntensity: 0.08,
      fogColor: '#3A3550',
      fogDensity: 0.012,
      gradeShadowMult: 0.7,
      gradeLightMix: 0.12,
      gradeShadowSat: 1.15,
    },
  },
  {
    id: 'act3',
    name: 'Act3 地铁隧道（应急灯）',
    note: '最暗的一幕。rim 0.60 是救命参数 —— 没有它深色敌人会直接消失在背景里。',
    apply: {
      keyAzimuth: 90,
      keyElevation: 30,
      keyIntensity: 0.75,
      keyColor: '#6FE08A',
      fillSkyColor: '#12241F',
      fillSkyIntensity: 0.18,
      fillGroundColor: '#0A1412',
      fillGroundIntensity: 0.08,
      rimColor: '#2BC4D6',
      rimIntensity: 0.6,
      ambientColor: '#081410',
      ambientIntensity: 0.06,
      fogColor: '#1E4034',
      fogDensity: 0.045,
      gradeShadowMult: 0.74,
      gradeShadowMix: 0.35,
      gradeLightMix: 0.12,
      gradeShadowSat: 1.18,
    },
  },
  {
    id: 'act4',
    name: 'Act4 生化医院（荧光）',
    note: '惨白荧光 + 毒紫补光。同样是顶光陷阱，角色光仰角要压到 40°。',
    apply: {
      keyAzimuth: -10,
      keyElevation: 78,
      keyIntensity: 0.95,
      keyColor: '#EAF6FF',
      fillSkyColor: '#3A2450',
      fillSkyIntensity: 0.3,
      fillGroundColor: '#241A30',
      fillGroundIntensity: 0.12,
      rimColor: '#9B5DE5',
      rimIntensity: 0.55,
      ambientColor: '#1A1226',
      ambientIntensity: 0.1,
      fogColor: '#3A2450',
      fogDensity: 0.025,
      gradeShadowMult: 0.8,
      gradeShadowMix: 0.24,
      gradeLightMix: 0.12,
      gradeShadowSat: 1.22,
      gradeMidSat: 1.2,
      gradeLightSat: 1.14,
    },
  },
];

export interface MaterialPreset {
  id: string;
  name: string;
  note: string;
  apply: Partial<MaterialState>;
}

/** 材质分类。数值来源：docs/07-灯光与材质系统.md §6。 */
export const MATERIAL_PRESETS: MaterialPreset[] = [
  {
    id: 'skin',
    name: 'skin 僵尸皮肤',
    note: '2 阶、暗部紫蓝偏移强、湿润高光、半调 1.2。主色 zombie 向黄绿，带血污。',
    apply: {
      albedo: '#8FD14F',
      roughness: 0.55,
      metallic: 0.0,
      emissiveColor: '#000000',
      emissiveStrength: 0,
      shadowEnd: -1,
      specMix: 0.18,
      softnessScale: 1.0,
      halftoneScale: 1.2,
      outlineScale: 1.0,
      unlit: false,
    },
  },
  {
    id: 'metal',
    name: 'metal 金属盾板',
    note: '高光阶强、暗部偏移弱、描边 1.5×、完全不要半调。冷灰 + teal 焊缝。',
    apply: {
      albedo: '#7A8290',
      roughness: 0.28,
      metallic: 0.95,
      emissiveColor: '#2BC4D6',
      emissiveStrength: 0.15,
      shadowEnd: -1,
      specMix: 0.55,
      softnessScale: 0.7,
      halftoneScale: 0.0,
      outlineScale: 1.5,
      unlit: false,
    },
  },
  {
    id: 'cloth',
    name: 'cloth 布料绷带',
    note: '2 阶但软边放大到 2.0，无高光。硬边分阶在布料上会显得像塑料。',
    apply: {
      albedo: '#C8B89A',
      roughness: 0.95,
      metallic: 0.0,
      emissiveColor: '#000000',
      emissiveStrength: 0,
      shadowEnd: -1,
      specMix: 0.0,
      softnessScale: 2.0,
      halftoneScale: 1.0,
      outlineScale: 1.0,
      unlit: false,
    },
  },
  {
    id: 'emissive',
    name: 'emissive 发光接口',
    note: '不分阶、unlit、直接输出 + 喂 bloom。脊椎接口和毒液走这个。',
    apply: {
      albedo: '#E8402A',
      roughness: 0.4,
      metallic: 0.0,
      emissiveColor: '#E8402A',
      emissiveStrength: 3.2,
      shadowEnd: 0.0,
      specMix: 0.0,
      softnessScale: 1.0,
      halftoneScale: 0.0,
      outlineScale: 1.0,
      unlit: true,
    },
  },
  {
    id: 'toxic',
    name: 'toxic 毒液',
    note: '毒紫自发光 + 中强度 bloom。B-02/B-03 与精英怪共用。',
    apply: {
      albedo: '#9B5DE5',
      roughness: 0.25,
      metallic: 0.0,
      emissiveColor: '#9B5DE5',
      emissiveStrength: 2.4,
      shadowEnd: 0.0,
      specMix: 0.4,
      softnessScale: 1.2,
      halftoneScale: 0.0,
      outlineScale: 0.75,
      unlit: false,
    },
  },
];
